/**
 * ESLint flat config (ESLint 9 + Next 16).
 *
 * Replaces `next lint`, which Next.js 16 removed in favor of running
 * ESLint directly. The official `eslint-config-next` package now ships
 * a `Linter.Config[]` array we spread alongside our own overrides.
 *
 * Layers, in order:
 *   1. Next.js base (React + jsx-a11y + import + plugin:next).
 *   2. Next.js core-web-vitals (stricter perf/a11y rules for Next apps).
 *   3. TypeScript (typescript-eslint parser + plugin for *.ts / *.tsx).
 *   4. Project-specific ignores (auto-generated SDK, build artefacts).
 *
 * `.mjs` extension because the project's package.json does not declare
 * `"type": "module"` — using ESM here avoids the `no-require-imports`
 * complaint when the typescript-eslint rules sweep the config file.
 *
 * Run: `npm run lint`. Auto-fix where possible: `npm run lint:fix`.
 */

import next from "eslint-config-next";
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

const config = [
  ...next,
  ...nextCoreWebVitals,
  ...nextTypeScript,
  {
    ignores: [
      // Generated OpenAPI client — regenerated by `npm run gen:api`,
      // never hand-edited. Gitignored but may exist locally.
      "src/lib/api/generated/**",
      // Build outputs (next.js's default config also ignores these,
      // listed here for clarity).
      ".next/**",
      "out/**",
      "build/**",
      "coverage/**",
      "playwright-report/**",
      "test-results/**",
    ],
  },
];

export default config;
